[build]
  command = "npm run build"
  publish = "dist"
  node_version = "18"

  [[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = 
    "default-src 'self'; script-src 'self''unsafe-eval' 'unsafe-inline'; 
     object-src 'none'; style-src 'self' 'unsafe-inline';"
